#!/usr/bin/env python3
import argparse, pathlib

TEMPLATE_CMAKELISTS = """cmake_minimum_required(VERSION 3.22)
project({name} LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 23)
add_executable({name} src/main.cpp)
"""

TEMPLATE_MAIN = '#include <iostream>\nint main(){ std::cout << "Hello from {name}\\n"; }\n'

def cmd_new(args):
    root = pathlib.Path(args.name)
    (root/"src").mkdir(parents=True, exist_ok=True)
    (root/"CMakeLists.txt").write_text(TEMPLATE_CMAKELISTS.format(name=args.name))
    (root/"src/main.cpp").write_text(TEMPLATE_MAIN.format(name=args.name))
    (root/"README.md").write_text(f"# {args.name}\nGenerated by forge-cpp.\n")
    print(f"✅ Created {args.name}")

def main():
    ap = argparse.ArgumentParser("forge")
    sub = ap.add_subparsers(dest="cmd", required=True)
    ap_new = sub.add_parser("new", help="Create a new C++ project")
    ap_new.add_argument("name")
    ap_new.set_defaults(func=cmd_new)
    args = ap.parse_args()
    args.func(args)

if __name__ == "__main__":
    main()
